### ISSUE TITLE
[Docker-compose Error] Cannot find module

### ISSUE THREAD

**Issue by YIPG** [TypeStrong/ts-node#843]
When I launch app in local, modules are correctly loaded. And also `docker-compose run yarn start` works well.

**However, `docker-compose up` always emit error.**

Can someone help me?

Error
```shell
/app/node_modules/ts-node/src/index.ts:243
api_1     |     return new TSError(diagnosticText, diagnosticCodes)
api_1     |            ^
api_1     | TSError: ⨯ Unable to compile TypeScript:
api_1     | app.ts(5,21): error TS2307: Cannot find module 'express-session'.
```
app.ts
```javascript
import express from 'express'
import mongoose from 'mongoose'
import cors from 'cors'
import route from './routes/route'
import session from 'express-session'
```
Dockerfile
```dockerfile
FROM node:10.16-alpine

WORKDIR /app

COPY package.json ./

COPY yarn.lock ./

RUN yarn install

COPY . .

CMD ["yarn", "start"]
```
docker-compose.yml
```yml
version: '3'
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - 27017:27017
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PORT=5000
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - api
    volumes:
      - /app/node_modules
      - ./client:/app

```
package.json
```json
{
  "scripts": {
    "start": "ts-node app.ts",
    "test": "jest"
  },
  "name": "myapp",
  "version": "1.0.0",
  "main": "app.ts",
  "license": "MIT",
  "dependencies": {
    "@types/express-session": "^1.15.12",
    "cors": "^2.8.5",
    "express": "^4.16.4",
    "express-session": "^1.16.2",
    "mongoose": "^5.5.5",
    "multer": "^1.4.1",
    "nodemon": "^1.18.11",
    "ts-node": "^8.0.3",
    "typescript": "^3.4.3"
  },
  "devDependencies": {
    "@types/body-parser": "^1.17.0",
    "@types/jest": "^24.0.14",
    "@types/mongoose": "^5.5.5",
    "@types/mysql": "^2.15.6",
    "jest": "^24.8.0",
    "ts-jest": "^24.0.2"
  }
}

```
tsconfig.json
```json
{
  "compilerOptions": {
    "outDir": "./dist",
    "sourceMap": true,
    "module": "es6",
    "target": "es5",
    "moduleResolution": "node",
    "removeComments": true
  },
}
```
